services:
  - type: web
    name: case-pratico
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app  # Usa gunicorn para produção
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.16  # Versão compatível com torch
startCommand: gunicorn --workers=1 --timeout=120 app:app